apiVersion: v1
kind: Service
metadata:
  name: boletoapi-master-service
spec:
  selector:
    app: boletoapi-master
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer