FROM maven:3.8.1-openjdk-17-slim AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn -f pom.xml clean package

FROM openjdk:17-slim
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE 8082

ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=arqsoft
CMD ["java", "-jar", "app.jar"]